### ISSUE TITLE
Ficheros log enormes

### ISSUE THREAD

**Issue by pgonzalez-git** [altiria/sms-java-client#1]
Hola,
Nos pusimos a trabajar con vuestra librería, y con el paso del tiempo nos hemos dado cuenta que se ha generado una carpeta llamada 'log' en la raíz de la aplicación, y los logs de dentro ocupan todos más de 1 giga provocando que se llene el disco muy rápido, son tan grandes porque parece que registra DEBUG y otros niveles de las transacciones con la BBDD de todos los packages. ¿Hay alguna forma de desactivar este log o esos niveles? Los ficheros generados se llaman sms-java-client.log
Gracias,
Un saludo,

**Comment by altiria** [comment]
Hola,
El nivel del log del paquete com.altiria.app es "debug" y es excesivo para un entorno de producción. Hemos cambiado el nivel por defecto a "error". Para una corrección rápida en tu sistema puedes modificar el archivo src/main/resources/log4j2.xml para asignar el nivel "error" para el log de la librería
